version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/QuikaV2-Dashboard
hooks:
  BeforeInstall:
    - location: preBuild.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: build.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: postBuild.sh
      timeout: 60
      runas: root
permissions:
  - object: /
    pattern: '*.sh'
    mode: 777
