version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/QuikaV2-Dashboard
hooks:
  AfterInstall:
    - location: build.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: postBuild.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root